# Generated by Django 3.2 on 2021-04-17 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('street', models.CharField(max_length=200, null=True)),
                ('number', models.CharField(max_length=200, null=True)),
                ('Postal_code', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=200, null=True)),
                ('website', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSID', models.IntegerField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=200, null=True)),
                ('first_dose', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.address')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.hospital')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='symptoms',
            field=models.ManyToManyField(to='hospitals.Symptom'),
        ),
        migrations.AddField(
            model_name='patient',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.vaccine'),
        ),
        migrations.CreateModel(
            name='AvailabeVaccines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.vaccine')),
            ],
        ),
    ]
