# Generated by Django 3.2 on 2021-04-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20210417_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='vac_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='company',
            field=models.CharField(choices=[('Pfizer', 'Pfizer'), ('AstraZeneca', 'AstraZeneca'), ('Moderna', 'Moderna'), ('Sputink', 'Sputink'), ('Johnson & Johnson', 'Johnson & Johnson')], max_length=200, null=True),
        ),
    ]
