# Generated by Django 3.2 on 2021-04-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_auto_20210417_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccine',
            old_name='company',
            new_name='name',
        ),
    ]
