# Generated by Django 3.2 on 2021-04-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_rename_company_vaccine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='doses',
            field=models.IntegerField(null=True),
        ),
    ]
