# Generated by Django 3.2 on 2021-04-20 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitals', '0006_vaccine_doses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabeVaccines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_amount', models.IntegerField(blank=True, default=-1, null=True)),
                ('reserved', models.IntegerField(blank=True, default=-1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='vaccine',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vaccination',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='name',
        ),
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='country',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='number',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='postal_code',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='street',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='user_hospital',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='age',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='completed_doses',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='first_dose_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='second_dose_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='ssid',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='symptoms',
            field=models.ManyToManyField(blank=True, null=True, to='hospitals.Symptom'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='vaccine_brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospitals.vaccine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccine',
            name='brand',
            field=models.CharField(blank=True, choices=[('Pfizer', 'Pfizer'), ('AstraZeneca', 'AstraZeneca'), ('Moderna', 'Moderna'), ('Sputink', 'Sputink'), ('Johnson & Johnson', 'Johnson & Johnson')], default='omg', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='website',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='doses',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AddField(
            model_name='availabevaccines',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='availabevaccines',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.vaccine'),
        ),
    ]
