# Generated by Django 3.2 on 2021-04-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_auto_20210420_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='brand',
            field=models.CharField(blank=True, choices=[('Pfizer', 'Pfizer'), ('AstraZeneca', 'AstraZeneca'), ('Moderna', 'Moderna'), ('Sputink', 'Sputink'), ('Johnson & Johnson', 'Johnson & Johnson')], default='', max_length=200, null=True),
        ),
    ]
