# Generated by Django 3.2 on 2021-04-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0008_alter_vaccine_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
