# Generated by Django 3.2 on 2021-04-18 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('street', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('number', models.IntegerField(blank=True, default=-1, null=True)),
                ('postal_code', models.IntegerField(blank=True, default=-1, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('doses', models.IntegerField(blank=True, default=-1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('age', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=50)),
                ('completed_doses', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0)),
                ('symptoms', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('first_dose_date', models.DateField(null=True)),
                ('second_dose_date', models.DateField(null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.hospital')),
                ('vaccine_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabeVaccines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_amount', models.IntegerField(blank=True, default=-1, null=True)),
                ('reserved', models.IntegerField(blank=True, default=-1, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.hospital')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.vaccine')),
            ],
        ),
    ]
