# Generated by Django 3.2 on 2021-04-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='user',
            new_name='user_hospital',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='address',
        ),
        migrations.AddField(
            model_name='hospital',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='website',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='postal_code',
            field=models.IntegerField(blank=True, default=-1, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='age',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='gender',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='vaccination',
            name='symptoms',
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='brand',
            field=models.CharField(blank=True, choices=[('Pfizer', 'Pfizer'), ('AstraZeneca', 'AstraZeneca'), ('Moderna', 'Moderna'), ('Sputink', 'Sputink'), ('Johnson & Johnson', 'Johnson & Johnson')], default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='symptoms',
            field=models.ManyToManyField(blank=True, null=True, to='application.Symptom'),
        ),
    ]
