# Generated by Django 3.2 on 2021-04-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210419_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='pending', max_length=50),
        ),
    ]
