# Generated by Django 3.2 on 2021-05-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_vaccine_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccination',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='country',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
