# Generated by Django 3.2 on 2021-05-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20210517_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
