# Generated by Django 2.2.12 on 2021-05-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20210525_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='private_key',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='public_key',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
