# Generated by Django 2.2.12 on 2021-05-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20210525_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabevaccines',
            name='free_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='availabevaccines',
            name='reserved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
