# Generated by Django 2.2.12 on 2021-05-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20210529_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='postal_code',
        ),
    ]
