# Generated by Django 2.2.12 on 2021-05-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_remove_hospital_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='second_dose_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
